server:
  port: 8000

spring:
  application:
    name: cloud-consumer-feign-hystrix-order

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

ribbon: # 设置 OpenFeign 客户端超时时间（OpenFeign 默认支持 Ribbon）
  ReadTimeout: 5000 # 客户端与服务端建立连接所用的时间
  ConnectTimeout: 5000 # 建立连接后 OpenFeign 客户端从服务器读取可用资源所用的时间

feign:
  hystrix:
    enabled: true